import json
import random
import requests
from tqdm import tqdm
from bs4 import BeautifulSoup

places_data = {"places": []}

names = [
    "Museu de Arte",
    "Parque Central",
    "Biblioteca Nacional",
    "Jardim Botânico",
    "Aquário",
    "Museu de História Natural",
    "Galeria de Arte",
    "Centro de Ciências",
    "Zoológico",
    "Parque de Diversões",
    "Teatro Municipal",
    "Monumento Histórico",
    "Museu de Ciência",
    "Centro Cultural",
    "Igreja Histórica",
    "Praça Central",
    "Mirante",
    "Catedral",
    "Estádio de Futebol",
    "Mercado Municipal",
    "Centro Esportivo",
    "Casa de Cultura",
    "Espaço de Eventos",
    "Fortaleza",
    "Palácio de Governo",
    "Estação Ferroviária",
    "Museu do Automóvel",
    "Parque Aquático",
    "Jardim Zoológico",
    "Planetário",
    "Museu do Índio",
    "Museu do Imigrante",
    "Observatório",
    "Museu do Trem",
    "Museu Naval",
    "Museu do Futebol",
    "Museu da Imagem e do Som",
    "Museu de Arte Contemporânea",
    "Museu de Arte Moderna",
    "Museu da Cidade",
    "Museu Histórico",
    "Museu de Ciências Naturais",
    "Museu de Ciências",
    "Museu da Ciência e Tecnologia",
    "Museu Arqueológico",
    "Museu da Inconfidência",
    "Museu Imperial",
    "Museu da Língua Portuguesa",
    "Museu da Casa Brasileira",
    "Museu do Café",
    "Museu do Homem do Nordeste",
    "Museu de Antropologia",
    "Museu de Geologia",
    "Museu de História",
    "Museu de Paleontologia",
    "Museu da Vida",
    "Museu da República",
    "Museu do Mar",
    "Museu Ferroviário",
    "Museu Histórico Nacional",
    "Museu do Estado",
    "Museu da Gente Sergipana",
    "Museu Histórico e Artístico",
    "Museu de Ciências e Tecnologia",
    "Museu de Arte Sacra",
    "Museu da Inconfidência Mineira",
    "Museu da Memória",
    "Museu da Revolução",
    "Museu do Sertão",
    "Museu de Zoologia",
    "Museu do Folclore",
    "Museu do Amanhã",
    "Museu Afro Brasil",
    "Museu de História da Medicina",
    "Museu do Universo",
    "Museu do Açúcar",
    "Museu do Sertão",
    "Museu do Vinho",
    "Museu do Chocolate",
    "Museu do Boi",
    "Museu do Carro",
    "Museu do Avião",
    "Museu da Aviação",
    "Museu do Trem",
    "Museu do Telefone",
    "Museu da Comunicação",
    "Museu da Tecnologia",
    "Museu do Computador",
    "Museu do Rádio",
    "Museu do Vídeo Game",
    "Museu da Música",
    "Museu do Teatro",
    "Museu da Moda",
    "Museu do Futebol Brasileiro",
    "Museu do Patrimônio Histórico",
    "Museu do Patrimônio Cultural",
    "Museu da Herança",
    "Museu das Comunicações",
    "Museu do Banco",
    "Museu do Trabalho",
    "Museu da Vida",
    "Museu do Corpo Humano",
]

locations = [
    "São Paulo",
    "Rio de Janeiro",
    "Belo Horizonte",
    "Brasília",
    "Salvador",
    "Fortaleza",
    "Curitiba",
    "Manaus",
    "Recife",
    "Belém",
    "Porto Alegre",
    "Goiânia",
    "Guarulhos",
    "Campinas",
    "São Luís",
    "São Gonçalo",
    "Maceió",
    "Duque de Caxias",
    "Natal",
    "Campo Grande",
    "Teresina",
    "São Bernardo do Campo",
    "Nova Iguaçu",
    "João Pessoa",
    "Santo André",
    "Osasco",
    "Jaboatão dos Guararapes",
    "Ribeirão Preto",
    "Uberlândia",
    "Contagem",
    "Sorocaba",
    "Aracaju",
    "Feira de Santana",
    "Cuiabá",
    "Joinville",
    "Aparecida de Goiânia",
    "Londrina",
    "Ananindeua",
    "Niterói",
    "Porto Velho",
    "Campos dos Goytacazes",
    "Mauá",
    "São José dos Campos",
    "Santos",
    "Diadema",
    "Mogi das Cruzes",
    "Betim",
    "Jundiaí",
    "Caxias do Sul",
    "Florianópolis",
    "Macapá",
    "Canoas",
    "Bauru",
    "Vitória",
    "São Vicente",
    "Pelotas",
    "Franca",
    "Blumenau",
    "Ponta Grossa",
    "Petrolina",
    "Campina Grande",
    "Boa Vista",
    "Piracicaba",
    "Montes Claros",
    "Rio Branco",
    "Santarém",
    "Cascavel",
    "Hortolândia",
    "Rondonópolis",
    "Palmas",
    "Várzea Grande",
    "Marabá",
    "Itaquaquecetuba",
    "Maringá",
    "Anápolis",
    "Barueri",
    "Vila Velha",
    "Volta Redonda",
    "Santa Maria",
    "Suzano",
    "Sete Lagoas",
    "Divinópolis",
    "Caruaru",
    "Ibirité",
    "Criciúma",
    "São José do Rio Preto",
    "Colombo",
    "Limeira",
    "Teófilo Otoni",
    "Sinop",
    "Itabuna",
    "Governador Valadares",
    "Marília",
    "Ipatinga",
    "Taboão da Serra",
    "Petrópolis",
    "Vitória da Conquista",
    "Sobral",
    "Indaiatuba",
    "Mossoró",
    "Cachoeiro de Itapemirim",
]


def get_image_url(place_name):
    search_url = "https://www.bing.com/images/search"
    params = {"q": place_name, "FORM": "HDRSC2"}
    response = requests.get(search_url, params=params)
    soup = BeautifulSoup(response.text, "html.parser")

    img_tag = soup.find("a", class_="iusc")
    if img_tag:
        img_url = img_tag.get("m")
        img_url = img_url.split('"murl":"')[1].split('"')[0]
        return img_url
    return None


ratings = [round(random.uniform(3.0, 5.0), 1) for _ in range(100)]
likes = [random.randint(50, 1000) for _ in range(100)]

for i in tqdm(range(1, 101)):
    name = random.choice(names)
    place = {
        "place_id": str(i),
        "name": name,
        "location": random.choice(locations),
        "rating": str(ratings[i - 1]),
        "likes": str(likes[i - 1]),
        "image": get_image_url(name) or "data/default.png",
    }
    places_data["places"].append(place)

json_data = json.dumps(places_data, indent=2, ensure_ascii=False)
with open("model/data/places.json", "w", encoding="utf-8") as file:
    file.write(json_data)
