from typing import Iterable
from model.types.basic_types import User, Place


class Repository:
    def __init__(self, conn_url: str | None = None): ...

    def get_by_id(self, user_id: str) -> User: ...

    def get_all(self) -> Iterable[User]: ...

    def update(self, user_id: str, data: User) -> None: ...

    def create(self, data: User) -> None: ...

    def delete(self, user_id: str) -> None: ...

    def get_place_by_id(self, place_id: str) -> Place | None: ...

    def get_all_places(self) -> Iterable[Place]: ...
