from typing import Iterable


class Repository:
    def __init__(self, conn_url: str | None = None): ...

    def get_by_id(self, user_id: str) -> dict: ...

    def get_all(self) -> Iterable[dict]: ...

    def update(self, user_id: str, data: dict) -> None: ...

    def create(self, data: dict) -> None: ...

    def delete(self, user_id: str) -> None: ...
